#adapted from example in docker documentation
version: '3'

services:
  web:
    build: .
    volumes:
       - .:/code
    expose:
       - 8000
    #user: 1001:1002
    command: python /code/myCalsite/manage.py runserver 0.0.0.0:8000

  nginx:
   restart: always
   build: ./nginx/
   depends_on:
      - web
   ports:
     - "80:80"
      #    - "443:443"
      # volumes:
      #    - ./myCalsite/myCalapp/static:/static
   links:
      - web:web