#adapted from example in docker documentation
version: '3'

services:
  web:
    build: .
    volumes:
       - .:/code
    ports:
       - 8000:8000
    user: 1000:1000
    command: python /code/myCalsite/manage.py runserver 0.0.0.0:8000

# nginx:
#  restart: always
#  build: ./nginx/
#  depends_on:
#    - web
#  ports:
#    - "80:80"
#    - "443:443"
