# Generated by Django 2.2.7 on 2019-12-04 05:16

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Event_group',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eventg_name', models.CharField(max_length=50)),
                ('eventg_startday', models.DateField(default=datetime.datetime.now)),
                ('eventg_starttime', models.TimeField(default='1')),
                ('eventg_endday', models.DateField(default=datetime.datetime.now)),
                ('eventg_endtime', models.TimeField(default='1')),
                ('eventg_location', models.CharField(max_length=50, null=True)),
                ('eventg_note', models.CharField(max_length=100, null=True)),
                ('eventg_tag', models.CharField(max_length=25, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Task_group',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('taskg_name', models.CharField(max_length=50)),
                ('taskg_duedate', models.DateTimeField(default=django.utils.timezone.now)),
                ('taskg_note', models.CharField(max_length=100, null=True)),
                ('taskg_tag', models.CharField(max_length=25, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='User_Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bio', models.TextField(default='', max_length=500, null=True)),
                ('user', models.OneToOneField(default='1', on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='User_Group',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_ID', models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Task_user',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tasku_name', models.CharField(max_length=50)),
                ('tasku_duedate', models.DateTimeField(default=django.utils.timezone.now)),
                ('tasku_note', models.CharField(max_length=100, null=True)),
                ('tasku_tag', models.CharField(max_length=25, null=True)),
                ('user_ID', models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Friendship',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('friends', models.ManyToManyField(default='1', related_name='friended', to='myCalapp.Friendship')),
                ('user', models.OneToOneField(default='1', on_delete=django.db.models.deletion.CASCADE, related_name='curruser', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Event_user',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eventu_name', models.CharField(max_length=50)),
                ('eventu_startday', models.DateField(default=datetime.datetime.now)),
                ('eventu_starttime', models.TimeField(default='1')),
                ('eventu_endday', models.DateField(default=datetime.datetime.now)),
                ('eventu_endtime', models.TimeField(default='1')),
                ('eventu_location', models.CharField(max_length=50, null=True)),
                ('eventu_note', models.CharField(max_length=100, null=True)),
                ('eventu_tag', models.CharField(max_length=25, null=True)),
                ('user_ID', models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
