# Generated by Django 2.2.7 on 2019-12-10 18:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myCalapp', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Event_group',
        ),
        migrations.DeleteModel(
            name='Task_group',
        ),
        migrations.DeleteModel(
            name='User_Group',
        ),
    ]
