# Generated by Django 2.2.5 on 2019-11-12 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myCalapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event_user',
            name='eventu_startday',
        ),
        migrations.AlterField(
            model_name='event_user',
            name='eventu_starttime',
            field=models.DateTimeField(),
        ),
    ]
