# Generated by Django 2.2.7 on 2019-12-24 04:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myCalapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatroom',
            name='name',
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
