# Generated by Django 2.2.5 on 2019-11-14 06:13

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myCalapp', '0002_auto_20191112_1826'),
    ]

    operations = [
        migrations.AddField(
            model_name='event_user',
            name='eventu_startday',
            field=models.DateField(default=datetime.datetime.now),
        ),
        migrations.AlterField(
            model_name='event_user',
            name='eventu_starttime',
            field=models.TimeField(default='1'),
        ),
    ]
