# Generated by Django 2.2.7 on 2019-12-10 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myCalapp', '0002_auto_20191210_1831'),
    ]

    operations = [
        migrations.CreateModel(
            name='Chatroom',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
    ]
