# Generated by Django 2.2.5 on 2019-11-14 18:07

import datetime
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('myCalapp', '0003_auto_20191114_0613'),
    ]

    operations = [
        migrations.CreateModel(
            name='User_Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('friend_ID', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='event_group',
            name='eventg_endday',
            field=models.DateField(default=datetime.datetime.now),
        ),
        migrations.AddField(
            model_name='event_group',
            name='eventg_startday',
            field=models.DateField(default=datetime.datetime.now),
        ),
        migrations.AlterField(
            model_name='event_group',
            name='eventg_endtime',
            field=models.TimeField(default='1'),
        ),
        migrations.AlterField(
            model_name='event_group',
            name='eventg_starttime',
            field=models.TimeField(default='1'),
        ),
        migrations.AlterField(
            model_name='task_group',
            name='taskg_duedate',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.AlterField(
            model_name='task_user',
            name='tasku_duedate',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.DeleteModel(
            name='User_Friends',
        ),
    ]
