# Generated by Django 2.2.5 on 2019-11-14 18:14

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('myCalapp', '0004_auto_20191114_1807'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task_group',
            name='taskg_duedate',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='task_user',
            name='tasku_duedate',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
